config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'welcome/index'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    resources :restaurants
  end
  resources :users do
    resources :ratings
  end
  resources :restaurants do
    resources :ratings, :only => [:index, :new, :create, :destroy, :edit, :update]
  end

  root "welcome#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rating.rb
class Rating < ApplicationRecord
  validates :stars, presence: true
  belongs_to :restaurant
  belongs_to :user

  def did_user_make_rating(id)
    self.user_id == id
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates :name, presence: true
  validates :location, presence: true
  validates :desc, presence: true
  # Destroys all related ratings on deletion
  has_many :ratings, dependent: :destroy
  belongs_to :user


  def get_average_rating
    calculate_average_rating
  end

  def prevent_multiple_ratings(id)
    self.ratings.each do |rating|
      if rating.user_id == id
        return true
      end
    end
    false
  end


  def did_i_make_this?(id)
    self.user_id == id
  end

  private

  def calculate_average_rating
    self.ratings.count == 0 ? "No ratings yet!" : ((self.ratings.inject(0){|sum, i| sum + i.stars} / (self.ratings.count).to_f).round(1))
  end


end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: {with: /@/}

  has_secure_password
  has_many :ratings, dependent: :destroy
  has_many :restaurants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
    @ratings = Rating.where(restaurant_id: params[:restaurant_id])
  end

  def new
    if !current_user()
      flash.keep[:errors] = "You must login to review a restaurant"
      redirect_to restaurant_ratings_path()
    end
  end

  def create
    restaurant = Restaurant.find(params[:restaurant_id])
    if restaurant.prevent_multiple_ratings(current_user.id)
      flash.keep[:danger] = "You have already rated this restaurant"
      redirect_to restaurant_path(restaurant.id)
    else
      @rating = Rating.new(rating_params.merge(restaurant_id: params[:restaurant_id], user_id: current_user().id))
      if @rating.save
        redirect_to restaurant_ratings_path()
      else
        render 'new'
      end
    end
  end

  def destroy
    @rating = Rating.find(params[:id])
    if @rating.did_user_make_rating(current_user.id)
      @rating.destroy()
      redirect_to restaurant_ratings_path(params[:restaurant_id])
    else
      redirect_to restaurant_path(@rating.restaurant_id)
    end
  end

  def edit
    @rating = Rating.find(params[:id])
    if @rating.did_user_make_rating(current_user.id)
    else
      redirect_to restaurant_path(@rating.restaurant_id)
    end
  end

  def update
    @rating = Rating.find(params[:id])
    if @rating.update(rating_params)
      redirect_to restaurant_ratings_path(@rating.restaurant_id)
    else
      render 'edit'
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:stars, :review)
  end

  def restaurant
    Restaurant.find(params[:restaurant_id])
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def index
    @restaurants = Restaurant.all()
  end

  def new

  end

  def create
    @restaurant = Restaurant.new(restaurant_params.merge(user_id: current_user().id))
    if @restaurant.save
      redirect_to "/"
    else
      render 'new'
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.did_i_make_this?(current_user.id)
      @restaurant.destroy()
      redirect_to restaurants_path
    else
      redirect_to restaurant_path(@restaurant.id)
    end

  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.did_i_make_this?(current_user.id)
    else
      redirect_to restaurant_path(@restaurant.id)
    end
  end


  def update
    @restaurant = Restaurant.find(params[:id])

      if @restaurant.update(restaurant_params)
        redirect_to "/"
      else
        render 'edit'
      end
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :location, :desc, :img)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def current_user
    if @current_user.nil?
      @current_user = User.find_by(id: session[:user_id])
    else
      @current_user
    end
  end

  def create
    p params
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to '/'
    else
      flash.now[:danger] = 'Invalid username/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to '/'
  end
end

app/controllers/users_controller.rb
require 'bcrypt'

class UsersController < ApplicationController
  def new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to '/'
    else
      redirect_to '/users/new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to '/'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @restaurants = Restaurant.all
    @username = session[:username]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yelp</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="jumbotron mainbar">
      <div class="row">
        <div class="col-sm-2">
        </div>
          <div class="col-sm-8" align="center">
            <a href="/" class="main-link">
              <div><h2 class="title">Ange.ry</h2><%= image_tag("banner.png", :class => "banner-pic")%></div>
            </a>
          </div>
        <div class="col-sm-2">
        </div>
      </div>
    </div>
    <nav class="row userbar" data-spy="affix" data-offset-top="146">
      <div class="col-sm-2">
        <div class="container-flex left-blank">
        </div>
      </div>
      <div class="col-sm-8">
        <div class="container-flex user-box">
          <% if logged_in? %>
          <ul>
            <div class="user-title"><p><%= @current_user.username %></p>
            <img src="<%= @current_user.userpic %>"></a></div>
              <li><%= link_to "Log out", logout_path, method: :delete %></li>
              <li><a href="/users/<%= current_user.id%>">My Reviews</a></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_path %></li>
              <li><%= link_to "Log in", sessions_new_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="col-sm-2">
        <div class="container-flex right-blank">
        </div>
      </div>
    </nav>
    <div id="errors">
      <% if flash[:errors] %>
        <%= flash[:errors] %>
      <% end %>
   </div>
    <%= yield %>

  </body>
</html>

app/views/ratings/edit.html.erb
<div class="row">
  <div class="col-sm-4">
  </div>
  <div class="col-sm-4 form-title">

    <%= form_for @rating, :html => {:class => 'main-form'}, url:{action: "update"} do |form| %>
      <p>
        <%= form.label :rating %><br>
        <fieldset class="rating">
        <label>
          <%= form.radio_button :stars, 1, id: "1" %>
          <%= image_tag("angry1.png", :id => "rating-faces")%>
        </label>
        <label>
        <%= form.radio_button :stars, 2, id: "2" %>
        <%= image_tag("angry1.png", :id => "rating-faces")%>
        </label>
        <label>
        <%= form.radio_button :stars, 3, id: "3" %>
        <%= image_tag("angry1.png", :id => "rating-faces")%>
        </label>
        <label>
        <%= form.radio_button :stars, 4, id: "4" %>
        <%= image_tag("angry1.png", :id => "rating-faces")%>
        </label>
        <label>
        <%= form.radio_button :stars, 5, id: "5" %>
        <%= image_tag("angry1.png", :id => "rating-faces")%>
        </label>
      </fieldset>

      </p>

      <p>
        <%= form.label :review %><br>
        <%= form.text_area :review %>
      </p>

      <p>
        <%= form.submit %>
      </p>
<% end %>
      <div class="col-sm-4">
    </div>
  </div>
</div>

app/views/ratings/index.html.erb
<div class="row">
  <div class="col-sm-2">
  </div>
  <div class="col-sm-8">
<h1 align="center"><%= pluralize(@ratings.count, "Review") %></h1>
  <div class="row">
<% @ratings.each do |rating| %>
  <div class="col-sm-4">
    <% user = User.find(rating.user_id) %>
    <strong>Review by: <%= user.username %></strong> <br>
    <strong>Rating:</strong> <%= rating.stars %>
    <p> <strong>Review:</strong> <%= rating.review %></p>
    <%if rating.did_user_make_rating(current_user.id) %>
    <p><%= link_to 'Destroy', user_rating_path(id: rating.id, user_id: rating.user_id, restaurant_id: rating.restaurant_id),
            method: :delete,
            data:{ confirm: 'Are you sure?' } %>
    </p>
    <p><%= link_to 'Edit', edit_user_rating_path(id: rating.id, user_id: rating.user_id) %></p>
    <% end %>
  </div>
<% end %>
</div>
<div class="col-sm-2">
</div>
</div>

app/views/ratings/new.html.erb
<div class="row">
  <div class="col-sm-4">
  </div>
  <div class="col-sm-4 form-title">
<%= form_with scope: :rating, url: restaurant_ratings_path, local: true do |form| %>
  <p>
    <%= form.label :rating %><br>
    <fieldset class="rating">
    <label>
      <%= form.radio_button :stars, 1, id: "1" %>
      <%= image_tag("angry1.png", :id => "rating-faces")%>
    </label>
    <label>
    <%= form.radio_button :stars, 2, id: "2" %>
    <%= image_tag("angry1.png", :id => "rating-faces")%>
    </label>
    <label>
    <%= form.radio_button :stars, 3, id: "3" %>
    <%= image_tag("angry1.png", :id => "rating-faces")%>
    </label>
    <label>
    <%= form.radio_button :stars, 4, id: "4" %>
    <%= image_tag("angry1.png", :id => "rating-faces")%>
    </label>
    <label>
    <%= form.radio_button :stars, 5, id: "5" %>
    <%= image_tag("angry1.png", :id => "rating-faces")%>
    </label>
  </fieldset>

  </p>

  <p>
    <%= form.label :review %><br>
    <%= form.text_area :review %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

      <div class="col-sm-4">
      </div>
    </div>
</div>

app/views/restaurants/edit.html.erb
<div class="row">
  <div class="col-sm-4">
  </div>
  <div class="col-sm-4 form-title">

    <h1>Edit Restaurant</h1>

    <%= form_for @restaurant, :html => {:class => 'main-form'} do |form| %>
      <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </p>

      <p>
        <%= form.label :location %> <br>
        <%= form.text_field :location %> <br>
      </p>

      <p>
        <%= form.label :desc %> <br>
        <%= form.text_field :desc %>
      </p>

      <p>
        <%= form.label :image %> <br>
        <%= form.url_field :img %>
      </p>

      <p>
        <%= form.submit %>
      </p>

    <% end %>
    <div class="col-sm-4">
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name%> </h1>
<ul>
  <li><p><%= @restaurant.location %></p></li>
  <li><p><%= @restaurant.desc %></p></li>
  <li><p><%= @restaurant.get_average_rating %></p></li>
  <% if @restaurant.get_average_rating != "No ratings yet!" %>
    <div>
      <% @restaurant.get_average_rating.round().times do %>
          <%= image_tag("angry1.png", :id => "rating-faces")%>
      <% end %>
    </div>
  <% end %>

    <%if @restaurant.did_i_make_this?(current_user.id) %>
      <li><p><%= link_to 'Destroy', restaurant_path(@restaurant),
            method: :delete,
            data:{ confirm: 'Are you sure?' } %>
    <p><%= link_to 'Edit', edit_restaurant_path(@restaurant) %></p>
    <% end %>
    <p><%= link_to 'Review', new_restaurant_rating_path(@restaurant.id) %></p>
    </ul>
  </div>
  <div class="col-sm-2">
  </div>
</div>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-sm-4">
  </div>
  <div class="col-sm-4 form-title">

<%= form_for @user do |form| %>
  <p>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </p>

  <p>
    <%= form.label :email %> <br>
    <%= form.text_field :email %> <br>
  </p>

  <p>
    <%= form.label :password %> <br>
    <%= form.password_field :password %>
  </p>

  <p>
    <%= form.label :password_confirmation %> <br>
    <%= form.password_field :password_confirmation %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>
</div>
<div class="col-sm-4">
</div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-sm-4">
  </div>
  <div class="col-sm-4 form-title">
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :html => {:class => 'main-form'}, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <p> Username:</br> <%= f.text_field :username%> </p>
    <fieldset class="user-icon">
      <p>Choose your fighter:</p>
      <div class="user-icon-buttons">
        <label>
          <%= f.radio_button :userpic, "angry-bobby.jpeg", id: "1" %>
          <%= image_tag("angry-bobby.jpeg")%>
        </label>
      </div>
      <div class="user-icon-buttons">
        <label>
          <%= f.radio_button :userpic, "angry-emoji.png", id: "2" %>
          <%= image_tag("angry-emoji.png")%>
        </label>
      </div>
      <div class="user-icon-buttons">
        <label>
          <%= f.radio_button :userpic, "angry-man.png", id: "3" %>
          <%= image_tag("angry-man.png")%>
        </label>
      </div>
      <div class="user-icon-buttons">
        <label>
          <%= f.radio_button :userpic, "angry-mike.jpg", id: "4" %>
          <%= image_tag("angry-mike.jpg")%>
        </label>
      </div>
      <div class="user-icon-buttons">
        <label>
          <%= f.radio_button :userpic, "angry-patrick.jpeg", id: "5" %>
          <%= image_tag("angry-patrick.jpeg")%>
        </label>
      </div>
      <div class="user-icon-buttons">
        <label>
          <%= f.radio_button :userpic, "angry-square.jpg", id: "6" %>
          <%= image_tag("angry-square.jpg")%>
        </label>
      </div>
      <div class="user-icon-buttons">
        <label>
          <%= f.radio_button :userpic, "angry-sun.jpg", id: "7" %>
          <%= image_tag("angry-sun.jpg")%>
        </label>
      </div>
    </fieldset>

    <p> Email:</br> <%= f.email_field :email%> </p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit :Signup %>
  <% end %>

</div>
<div class="col-sm-4">
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-8">
      <h1> <%= @user.username %>'s reviews </h1>
      <div class="row">
        <% @user.ratings.each do |rating| %>
        <div class="col-sm-4">
          <p><%= Restaurant.find(rating.restaurant_id).name %></p>
          <ul>
            <li><p>Rating: <%= rating.stars %></p></li>
            <li><p>Review: <%= rating.review %></p></li>
            <%if @user.id == params[:id].to_i %>
            <li><p><%= link_to 'Destroy', user_rating_path(id: rating.id, user_id: rating.user_id, restaurant_id: rating.restaurant_id),
                  method: :delete,
                  data:{ confirm: 'Are you sure?' } %>
          <p><%= link_to 'Edit', edit_restaurant_rating_path(id: rating.id, user_id: rating.user_id, restaurant_id: rating.restaurant_id) %></p>

            </p></li>
            <% end %>
          </ul>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-sm-2">
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
    </div>
    <div class="col-sm-8">
    <h1 align="center"> Restaurants </h1>
    <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-sm-4">
        <a href="/restaurants/<%=restaurant.id%>">
        <div class="restaurant-box">
          <% if restaurant.img != "" %>
            <div class="restaurant-image-box" style="background: url(<%=restaurant.img %>)50% 50% no-repeat;">
          <% else %>
            <div class="restaurant-box-no-image" style="background-color: <%= ['#FFDC6A', '#F65966', '#FB9C69', '#FEBE69', '#FA8969', '#FFCC6A'].sample %>">
          <% end %>
            <h2 class="tile-title"><%= restaurant.name %></h2>
            <ul>
              <li><p><%= restaurant.location %></p></li>
              <li><p><%= restaurant.desc[0..40] %>...</p></li>
              <li><p><%= restaurant.get_average_rating %></p></li>
            </ul>
                <!-- <li><p><%= link_to 'Destroy', restaurant_path(restaurant),
                    method: :delete,
                    data:{ confirm: 'Are you sure?' } %>
                <p><%= link_to 'Edit', edit_restaurant_path(restaurant) %></p>
            </p></li> -->

          </div>
        </div>
      </a>
      </div>
    <% end %>

</div>
<div class="col-sm-2">
</div>
</div>
</div>